import { Header } from "@/components/header";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"], weight: ["400", "700", "800"], variable: "--font-inter" });

export const metadata: Metadata = {
  title: "News Homepage",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${inter.className} font-sans text-[15px] text-neutral-darkBlue`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
